go get -u golang.org/x/crypto/bcrypt
go get -u golang.org/x/crypto/blowfish
go get -u golang.org/x/crypto/bn256
go get -u golang.org/x/crypto/cast5
go get -u golang.org/x/crypto/curve25519
go get -u golang.org/x/crypto/hkdf
go get -u golang.org/x/crypto/md4
go get -u golang.org/x/crypto/nacl/box
go get -u golang.org/x/crypto/nacl/secretbox
go get -u golang.org/x/crypto/ocsp
go get -u golang.org/x/crypto/openpgp
go get -u golang.org/x/crypto/openpgp/armor
go get -u golang.org/x/crypto/openpgp/clearsign
go get -u golang.org/x/crypto/openpgp/elgamal
go get -u golang.org/x/crypto/openpgp/errors
go get -u golang.org/x/crypto/openpgp/packet
go get -u golang.org/x/crypto/openpgp/s2k
go get -u golang.org/x/crypto/otr
go get -u golang.org/x/crypto/pbkdf2
go get -u golang.org/x/crypto/poly1305
go get -u golang.org/x/crypto/ripemd160
go get -u golang.org/x/crypto/salsa20
go get -u golang.org/x/crypto/salsa20/salsa
go get -u golang.org/x/crypto/scrypt
go get -u golang.org/x/crypto/sha3
go get -u golang.org/x/crypto/ssh
go get -u golang.org/x/crypto/ssh/agent
go get -u golang.org/x/crypto/ssh/terminal
go get -u golang.org/x/crypto/ssh/test
go get -u golang.org/x/crypto/twofish
go get -u golang.org/x/crypto/xtea
go get -u golang.org/x/crypto/xts

go get -u golang.org/x/image/bmp
go get -u golang.org/x/image/riff
go get -u golang.org/x/image/tiff
go get -u golang.org/x/image/tiff/lzw
go get -u golang.org/x/image/vp8
go get -u golang.org/x/image/vp8l
go get -u golang.org/x/image/webp
go get -u golang.org/x/image/webp/nycbcra

go get -u golang.org/x/net/context
go get -u golang.org/x/net/dict
go get -u golang.org/x/net/html
go get -u golang.org/x/net/html/atom
go get -u golang.org/x/net/html/charset
go get -u golang.org/x/net/icmp
go get -u golang.org/x/net/idna
go get -u golang.org/x/net/internal/iana
go get -u golang.org/x/net/internal/nettest
go get -u golang.org/x/net/ipv4
go get -u golang.org/x/net/ipv6
go get -u golang.org/x/net/netutil
go get -u golang.org/x/net/proxy
go get -u golang.org/x/net/publicsuffix
go get -u golang.org/x/net/spdy
go get -u golang.org/x/net/webdav
go get -u golang.org/x/net/websocket

go get -u golang.org/x/sys/plan9
go get -u golang.org/x/sys/unix
go get -u golang.org/x/sys/windows

go get -u golang.org/x/text/cases
go get -u golang.org/x/text/cldr
go get -u golang.org/x/text/collate
go get -u golang.org/x/text/collate/build
go get -u golang.org/x/text/collate/colltab
go get -u golang.org/x/text/display
go get -u golang.org/x/text/encoding
go get -u golang.org/x/text/encoding/charmap
go get -u golang.org/x/text/encoding/japanese
go get -u golang.org/x/text/encoding/korean
go get -u golang.org/x/text/encoding/simplifiedchinese
go get -u golang.org/x/text/encoding/traditionalchinese
go get -u golang.org/x/text/encoding/unicode
go get -u golang.org/x/text/language
go get -u golang.org/x/text/transform
go get -u golang.org/x/text/unicode/norm

go get -u golang.org/x/tools/astutil
go get -u golang.org/x/tools/blog
go get -u golang.org/x/tools/blog/atom
go get -u golang.org/x/tools/cmd/benchcmp
go get -u golang.org/x/tools/cmd/callgraph
go get -u golang.org/x/tools/cmd/cover
go get -u golang.org/x/tools/cmd/digraph
go get -u golang.org/x/tools/cmd/eg
go get -u golang.org/x/tools/cmd/godex
go get -u golang.org/x/tools/cmd/godoc
go get -u golang.org/x/tools/cmd/goimports
go get -u golang.org/x/tools/cmd/gorename
go get -u golang.org/x/tools/cmd/gotype
go get -u golang.org/x/tools/cmd/html2article
go get -u golang.org/x/tools/cmd/oracle
go get -u golang.org/x/tools/cmd/present
go get -u golang.org/x/tools/cmd/ssadump
go get -u golang.org/x/tools/cmd/stringer
go get -u golang.org/x/tools/cmd/vet
go get -u golang.org/x/tools/cmd/vet/whitelist
go get -u golang.org/x/tools/container/intsets
go get -u golang.org/x/tools/cover
go get -u golang.org/x/tools/dashboard/builder
go get -u golang.org/x/tools/dashboard/updater
go get -u golang.org/x/tools/dashboard/watcher
go get -u golang.org/x/tools/go/buildutil
go get -u golang.org/x/tools/go/callgraph
go get -u golang.org/x/tools/go/callgraph/cha
go get -u golang.org/x/tools/go/callgraph/rta
go get -u golang.org/x/tools/go/callgraph/static
go get -u golang.org/x/tools/go/exact
go get -u golang.org/x/tools/go/gccgoimporter
go get -u golang.org/x/tools/go/gcimporter
go get -u golang.org/x/tools/go/importer
go get -u golang.org/x/tools/go/loader
go get -u golang.org/x/tools/go/pointer
go get -u golang.org/x/tools/go/ssa
go get -u golang.org/x/tools/go/ssa/interp
go get -u golang.org/x/tools/go/ssa/ssautil
go get -u golang.org/x/tools/go/types
go get -u golang.org/x/tools/go/types/typeutil
go get -u golang.org/x/tools/go/vcs
go get -u golang.org/x/tools/godoc
go get -u golang.org/x/tools/godoc/analysis
go get -u golang.org/x/tools/godoc/redirect
go get -u golang.org/x/tools/godoc/static
go get -u golang.org/x/tools/godoc/util
go get -u golang.org/x/tools/godoc/vfs
go get -u golang.org/x/tools/godoc/vfs/gatefs
go get -u golang.org/x/tools/godoc/vfs/httpfs
go get -u golang.org/x/tools/godoc/vfs/mapfs
go get -u golang.org/x/tools/godoc/vfs/zipfs
go get -u golang.org/x/tools/imports
go get -u golang.org/x/tools/oracle
go get -u golang.org/x/tools/oracle/serial
go get -u golang.org/x/tools/playground
go get -u golang.org/x/tools/playground/socket
go get -u golang.org/x/tools/present
go get -u golang.org/x/tools/refactor/eg
go get -u golang.org/x/tools/refactor/importgraph
go get -u golang.org/x/tools/refactor/lexical
go get -u golang.org/x/tools/refactor/rename
go get -u golang.org/x/tools/refactor/satisfy

go get -u golang.org/x/exp/ebnf
go get -u golang.org/x/exp/ebnflint
go get -u golang.org/x/exp/fsnotify
go get -u golang.org/x/exp/inotify
go get -u golang.org/x/exp/locale/search
go get -u golang.org/x/exp/old/netchan
go get -u golang.org/x/exp/utf8string
go get -u golang.org/x/exp/winfsnotify